import {guard} from '../core/auth-guard.js';
import {toast} from '../core/ui.js';
const library=document.querySelector('#mcLibrary'),stage=document.querySelector('#mcStage');
const tools=[
 ['item','🗡️','Custom Item','Build an editable /give item command.'],
 ['kit','🛡️','PvP / Survival Kit','Create a starter kit command set.'],
 ['enchant','✨','Enchant Helper','Generate an enchant command for a held item.'],
 ['potion','🧪','Potion Helper','Create a potion effect command.'],
 ['teleport','📍','Teleport','Build a simple teleport command.'],
 ['effect','💫','Effect','Generate a timed player effect command.'],
 ['gamerule','⚙️','GameRule','Create common gamerule commands.'],
 ['time','☀️','Time & Weather','Generate time or weather commands.'],
 ['summon','🐺','Summon','Build a basic entity summon command.'],
 ['fill','🧱','Fill Helper','Generate a fill command for an area.'],
 ['give','🎁','Give Item','Quickly create a simple give command.'],
 ['clone','📦','Clone Helper','Generate a clone command between coordinates.']
];
function render(){library.innerHTML=tools.map(([id,i,n,d])=>`<button class="mc-choice" data-mc="${id}"><div class="mc-art">${i}</div><h3>${n}</h3><p>${d}</p></button>`).join('');library.querySelectorAll('[data-mc]').forEach(b=>b.onclick=()=>open(b.dataset.mc))}
function head(id){const x=tools.find(a=>a[0]===id);document.querySelector('#mcTitle').textContent=x[2];document.querySelector('#mcDesc').textContent=x[3];library.querySelectorAll('.mc-choice').forEach(b=>b.classList.toggle('active',b.dataset.mc===id))}
function panel(x){stage.innerHTML='<div class="mc-panel">'+x+'</div>'}
function output(text){const o=document.querySelector('#mcOutput');o.value=text;document.querySelector('#mcCopy').onclick=()=>navigator.clipboard?.writeText(o.value).then(()=>toast('Command copied','good'))}
function common(){return '<div class="mc-actions"><button class="btn btn-primary" id="mcGenerate">Generate</button><button class="btn btn-ghost" id="mcCopy">Copy</button></div><textarea id="mcOutput" class="command-box" readonly></textarea>'}
function open(id){head(id);const r={item,kit,enchant,potion,teleport,effect,gamerule,time,summon,fill,give,clone};r[id]()}
function item(){panel('<div class="form-grid"><div class="field"><label>Item ID</label><select id="item"><option>netherite_sword</option><option>netherite_pickaxe</option><option>netherite_chestplate</option><option>diamond_sword</option><option>diamond_pickaxe</option><option>bow</option><option>shield</option></select></div><div class="field"><label>Amount</label><input id="amount" type="number" value="1" min="1" max="64"></div><div class="field"><label>Custom name</label><input id="iname" placeholder="JMB Item"></div><div class="field"><label>Unbreaking level</label><input id="unbreaking" type="number" min="0" max="255" value="0"></div><div class="field"><label>Sharpness level</label><input id="sharpness" type="number" min="0" max="255" value="0"></div><div class="field"><label>Efficiency level</label><input id="efficiency" type="number" min="0" max="255" value="0"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const item=document.querySelector('#item').value,a=document.querySelector('#amount').value,n=document.querySelector('#iname').value.trim().replace(/"/g,'\\"'),u=Number(document.querySelector('#unbreaking').value),s=Number(document.querySelector('#sharpness').value),e=Number(document.querySelector('#efficiency').value);let ench=[];if(u)ench.push(`minecraft:unbreaking:${u}`);if(s)ench.push(`minecraft:sharpness:${s}`);if(e)ench.push(`minecraft:efficiency:${e}`);let cmd=`/give @p minecraft:${item}[`;if(n)cmd+=`custom_name='{"text":"${n}"}'`;if(ench.length)cmd+=(n?',':'')+`enchantments={levels:{${ench.join(',')}}}`;cmd+=`] ${a}`;output(cmd)}}
function kit(){panel('<div class="field"><label>Kit type</label><select id="kit"><option value="survival">Survival</option><option value="netherite">Netherite</option><option value="builder">Builder</option><option value="starter">Starter</option></select></div><div class="field"><label>Player selector</label><input id="player" value="@p"></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const p=document.querySelector('#player').value||'@p',k=document.querySelector('#kit').value;const kits={starter:[`/give ${p} minecraft:stone_sword 1`,`/give ${p} minecraft:bread 16`,`/give ${p} minecraft:iron_pickaxe 1`],survival:[`/give ${p} minecraft:diamond_sword 1`,`/give ${p} minecraft:diamond_pickaxe 1`,`/give ${p} minecraft:shield 1`],netherite:[`/give ${p} minecraft:netherite_sword 1`,`/give ${p} minecraft:netherite_pickaxe 1`,`/give ${p} minecraft:netherite_chestplate 1`],builder:[`/give ${p} minecraft:stone 64`,`/give ${p} minecraft:glass 64`,`/give ${p} minecraft:water_bucket 1`]};output(kits[k].join('\n'))}}
function enchant(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Enchantment</label><select id="e"><option>minecraft:sharpness</option><option>minecraft:efficiency</option><option>minecraft:unbreaking</option><option>minecraft:fortune</option><option>minecraft:protection</option><option>minecraft:mending</option></select></div><div class="field"><label>Level</label><input id="l" type="number" min="1" max="255" value="5"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/enchant ${document.querySelector('#p').value||'@p'} ${document.querySelector('#e').value} ${Math.max(1,Math.min(255,Number(document.querySelector('#l').value))) }`)}
function potion(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Effect</label><select id="e"><option>minecraft:speed</option><option>minecraft:strength</option><option>minecraft:haste</option><option>minecraft:jump_boost</option><option>minecraft:regeneration</option></select></div><div class="field"><label>Seconds</label><input id="s" type="number" value="60"></div><div class="field"><label>Amplifier</label><input id="a" type="number" value="1" min="1" max="255"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/effect give ${document.querySelector('#p').value||'@p'} ${document.querySelector('#e').value} ${document.querySelector('#s').value} ${Math.max(0,Number(document.querySelector('#a').value)-1)}`)}
function teleport(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>X</label><input id="x" value="0"></div><div class="field"><label>Y</label><input id="y" value="100"></div><div class="field"><label>Z</label><input id="z" value="0"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/tp ${document.querySelector('#p').value||'@p'} ${document.querySelector('#x').value} ${document.querySelector('#y').value} ${document.querySelector('#z').value}`)}
function effect(){potion()}
function gamerule(){panel('<div class="form-grid"><div class="field"><label>Rule</label><select id="r"><option>keepInventory</option><option>doDaylightCycle</option><option>doWeatherCycle</option><option>mobGriefing</option><option>doMobSpawning</option><option>naturalRegeneration</option></select></div><div class="field"><label>Value</label><select id="v"><option>true</option><option>false</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/gamerule ${document.querySelector('#r').value} ${document.querySelector('#v').value}`)}
function time(){panel('<div class="form-grid"><div class="field"><label>Command</label><select id="t"><option value="day">Day</option><option value="night">Night</option><option value="noon">Noon</option><option value="midnight">Midnight</option><option value="clear">Clear weather</option><option value="rain">Rain</option><option value="thunder">Thunder</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const v=document.querySelector('#t').value;output(['clear','rain','thunder'].includes(v)?`/weather ${v}`:`/time set ${v}`)}}
function summon(){panel('<div class="form-grid"><div class="field"><label>Entity</label><select id="e"><option>minecraft:wolf</option><option>minecraft:horse</option><option>minecraft:villager</option><option>minecraft:iron_golem</option><option>minecraft:chicken</option></select></div><div class="field"><label>X</label><input id="x" value="~"></div><div class="field"><label>Y</label><input id="y" value="~"></div><div class="field"><label>Z</label><input id="z" value="~"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/summon ${document.querySelector('#e').value} ${document.querySelector('#x').value} ${document.querySelector('#y').value} ${document.querySelector('#z').value}`)}
function fill(){panel('<div class="form-grid">'+['x1','y1','z1','x2','y2','z2'].map(id=>`<div class="field"><label>${id.toUpperCase()}</label><input id="${id}" value="~"></div>`).join('')+'<div class="field"><label>Block</label><input id="block" value="minecraft:stone"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/fill ${['x1','y1','z1','x2','y2','z2'].map(id=>document.querySelector('#'+id).value).join(' ')} ${document.querySelector('#block').value} replace`)}
function give(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Item</label><input id="i" value="minecraft:diamond"></div><div class="field"><label>Amount</label><input id="a" type="number" value="1" min="1" max="64"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/give ${document.querySelector('#p').value||'@p'} ${document.querySelector('#i').value} ${document.querySelector('#a').value}`)}
function clone(){panel('<div class="form-grid">'+['x1','y1','z1','x2','y2','z2','dx','dy','dz'].map(id=>`<div class="field"><label>${id.toUpperCase()}</label><input id="${id}" value="~"></div>`).join('')+'</div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/clone ${['x1','y1','z1','x2','y2','z2','dx','dy','dz'].map(id=>document.querySelector('#'+id).value).join(' ')}`)}
await guard();render();open('item');
