import {guard} from '../core/auth-guard.js';
import {toast} from '../core/ui.js';
const library=document.querySelector('#mcLibrary'),stage=document.querySelector('#mcStage');
const tools=[
 ['item','🗡️','Custom Item','Build an editable /give item command.'],
 ['kit','🛡️','PvP / Survival Kit','Create a starter kit command set.'],
 ['enchant','✨','Enchant Helper','Generate an enchant command for a held item.'],
 ['potion','🧪','Potion Helper','Create a potion effect command.'],
 ['teleport','📍','Teleport','Build a simple teleport command.'],
 ['effect','💫','Effect','Generate a timed player effect command.'],
 ['gamerule','⚙️','GameRule','Create common gamerule commands.'],
 ['time','☀️','Time & Weather','Generate time or weather commands.'],
 ['summon','🐺','Summon','Build a basic entity summon command.'],
 ['fill','🧱','Fill Helper','Generate a fill command for an area.'],
 ['give','🎁','Give Item','Quickly create a simple give command.'],
 ['clone','📦','Clone Helper','Generate a clone command between coordinates.'],
 ['title','📝','Title Generator','Create title and subtitle commands.'],
 ['tellraw','💬','Tellraw Builder','Create a JSON chat message.'],
 ['particle','✨','Particle Helper','Generate a particle command.'],
 ['execute','⚙️','Execute Builder','Build a simple execute command.'],
 ['setblock','🧱','SetBlock','Place a block at coordinates.'],
 ['scoreboard','📊','Scoreboard','Create common scoreboard commands.'],
 ['worldborder','🌐','World Border','Create border size and center commands.'],
 ['locate','🧭','Locate Helper','Generate structure locate commands.'],
 ['advancement','🏆','Advancement Helper','Build advancement grant/revoke commands.'],
 ['clear','🧹','Clear Inventory','Generate safe clear commands.'],
 ['kick','🚪','Kick Helper','Build a kick command with a reason.'],
 ['ban','🔨','Ban Helper','Build a ban command with a reason.'],
 ['whitelist','📋','Whitelist Helper','Generate whitelist commands.'],
 ['spawnpoint','🛏️','Spawnpoint','Set a player spawn point.'],
 ['setworldspawn','🌍','World Spawn','Set the world spawn position.'],
 ['difficulty','⚔️','Difficulty','Generate difficulty commands.']
];
function render(){library.innerHTML=tools.map(([id,i,n,d])=>`<button class="mc-choice" data-mc="${id}"><div class="mc-art">${i}</div><h3>${n}</h3><p>${d}</p><span class="pill">Open →</span></button>`).join('');library.querySelectorAll('[data-mc]').forEach(b=>b.onclick=()=>open(b.dataset.mc))}
function head(id){const x=tools.find(a=>a[0]===id);document.querySelector('#mcTitle').textContent=x[2];document.querySelector('#mcDesc').textContent=x[3];library.querySelectorAll('.mc-choice').forEach(b=>b.classList.toggle('active',b.dataset.mc===id))}
function panel(x){stage.innerHTML='<div class="mc-panel">'+x+'</div>'}
function output(text){const o=document.querySelector('#mcOutput');o.value=text;document.querySelector('#mcCopy').onclick=()=>navigator.clipboard?.writeText(o.value).then(()=>toast('Command copied','good'))}
function common(){return '<div class="mc-actions"><button class="btn btn-primary" id="mcGenerate">Generate</button><button class="btn btn-ghost" id="mcCopy">Copy</button></div><textarea id="mcOutput" class="command-box" readonly></textarea>'}
function open(id){head(id);const r={item,kit,enchant,potion,teleport,effect,gamerule,time,summon,fill,give,clone};r[id]()}
function item(){panel('<div class="form-grid"><div class="field"><label>Item ID</label><select id="item"><option>netherite_sword</option><option>netherite_pickaxe</option><option>netherite_chestplate</option><option>diamond_sword</option><option>diamond_pickaxe</option><option>bow</option><option>shield</option></select></div><div class="field"><label>Amount</label><input id="amount" type="number" value="1" min="1" max="64"></div><div class="field"><label>Custom name</label><input id="iname" placeholder="JMB Item"></div><div class="field"><label>Unbreaking level</label><input id="unbreaking" type="number" min="0" max="255" value="0"></div><div class="field"><label>Sharpness level</label><input id="sharpness" type="number" min="0" max="255" value="0"></div><div class="field"><label>Efficiency level</label><input id="efficiency" type="number" min="0" max="255" value="0"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const item=document.querySelector('#item').value,a=document.querySelector('#amount').value,n=document.querySelector('#iname').value.trim().replace(/"/g,'\\"'),u=Number(document.querySelector('#unbreaking').value),s=Number(document.querySelector('#sharpness').value),e=Number(document.querySelector('#efficiency').value);let ench=[];if(u)ench.push(`minecraft:unbreaking:${u}`);if(s)ench.push(`minecraft:sharpness:${s}`);if(e)ench.push(`minecraft:efficiency:${e}`);let cmd=`/give @p minecraft:${item}[`;if(n)cmd+=`custom_name='{"text":"${n}"}'`;if(ench.length)cmd+=(n?',':'')+`enchantments={levels:{${ench.join(',')}}}`;cmd+=`] ${a}`;output(cmd)}}
function kit(){panel('<div class="field"><label>Kit type</label><select id="kit"><option value="survival">Survival</option><option value="netherite">Netherite</option><option value="builder">Builder</option><option value="starter">Starter</option></select></div><div class="field"><label>Player selector</label><input id="player" value="@p"></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const p=document.querySelector('#player').value||'@p',k=document.querySelector('#kit').value;const kits={starter:[`/give ${p} minecraft:stone_sword 1`,`/give ${p} minecraft:bread 16`,`/give ${p} minecraft:iron_pickaxe 1`],survival:[`/give ${p} minecraft:diamond_sword 1`,`/give ${p} minecraft:diamond_pickaxe 1`,`/give ${p} minecraft:shield 1`],netherite:[`/give ${p} minecraft:netherite_sword 1`,`/give ${p} minecraft:netherite_pickaxe 1`,`/give ${p} minecraft:netherite_chestplate 1`],builder:[`/give ${p} minecraft:stone 64`,`/give ${p} minecraft:glass 64`,`/give ${p} minecraft:water_bucket 1`]};output(kits[k].join('\n'))}}
function enchant(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Enchantment</label><select id="e"><option>minecraft:sharpness</option><option>minecraft:efficiency</option><option>minecraft:unbreaking</option><option>minecraft:fortune</option><option>minecraft:protection</option><option>minecraft:mending</option></select></div><div class="field"><label>Level</label><input id="l" type="number" min="1" max="255" value="5"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/enchant ${document.querySelector('#p').value||'@p'} ${document.querySelector('#e').value} ${Math.max(1,Math.min(255,Number(document.querySelector('#l').value))) }`)}
function potion(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Effect</label><select id="e"><option>minecraft:speed</option><option>minecraft:strength</option><option>minecraft:haste</option><option>minecraft:jump_boost</option><option>minecraft:regeneration</option></select></div><div class="field"><label>Seconds</label><input id="s" type="number" value="60"></div><div class="field"><label>Amplifier</label><input id="a" type="number" value="1" min="1" max="255"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/effect give ${document.querySelector('#p').value||'@p'} ${document.querySelector('#e').value} ${document.querySelector('#s').value} ${Math.max(0,Number(document.querySelector('#a').value)-1)}`)}
function teleport(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>X</label><input id="x" value="0"></div><div class="field"><label>Y</label><input id="y" value="100"></div><div class="field"><label>Z</label><input id="z" value="0"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/tp ${document.querySelector('#p').value||'@p'} ${document.querySelector('#x').value} ${document.querySelector('#y').value} ${document.querySelector('#z').value}`)}
function effect(){potion()}
function gamerule(){panel('<div class="form-grid"><div class="field"><label>Rule</label><select id="r"><option>keepInventory</option><option>doDaylightCycle</option><option>doWeatherCycle</option><option>mobGriefing</option><option>doMobSpawning</option><option>naturalRegeneration</option></select></div><div class="field"><label>Value</label><select id="v"><option>true</option><option>false</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/gamerule ${document.querySelector('#r').value} ${document.querySelector('#v').value}`)}
function time(){panel('<div class="form-grid"><div class="field"><label>Command</label><select id="t"><option value="day">Day</option><option value="night">Night</option><option value="noon">Noon</option><option value="midnight">Midnight</option><option value="clear">Clear weather</option><option value="rain">Rain</option><option value="thunder">Thunder</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>{const v=document.querySelector('#t').value;output(['clear','rain','thunder'].includes(v)?`/weather ${v}`:`/time set ${v}`)}}
function summon(){panel('<div class="form-grid"><div class="field"><label>Entity</label><select id="e"><option>minecraft:wolf</option><option>minecraft:horse</option><option>minecraft:villager</option><option>minecraft:iron_golem</option><option>minecraft:chicken</option></select></div><div class="field"><label>X</label><input id="x" value="~"></div><div class="field"><label>Y</label><input id="y" value="~"></div><div class="field"><label>Z</label><input id="z" value="~"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/summon ${document.querySelector('#e').value} ${document.querySelector('#x').value} ${document.querySelector('#y').value} ${document.querySelector('#z').value}`)}
function fill(){panel('<div class="form-grid">'+['x1','y1','z1','x2','y2','z2'].map(id=>`<div class="field"><label>${id.toUpperCase()}</label><input id="${id}" value="~"></div>`).join('')+'<div class="field"><label>Block</label><input id="block" value="minecraft:stone"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/fill ${['x1','y1','z1','x2','y2','z2'].map(id=>document.querySelector('#'+id).value).join(' ')} ${document.querySelector('#block').value} replace`)}
function give(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="p" value="@p"></div><div class="field"><label>Item</label><input id="i" value="minecraft:diamond"></div><div class="field"><label>Amount</label><input id="a" type="number" value="1" min="1" max="64"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/give ${document.querySelector('#p').value||'@p'} ${document.querySelector('#i').value} ${document.querySelector('#a').value}`)}
function clone(){panel('<div class="form-grid">'+['x1','y1','z1','x2','y2','z2','dx','dy','dz'].map(id=>`<div class="field"><label>${id.toUpperCase()}</label><input id="${id}" value="~"></div>`).join('')+'</div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(`/clone ${['x1','y1','z1','x2','y2','z2','dx','dy','dz'].map(id=>document.querySelector('#'+id).value).join(' ')}`)}

function title(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="tp" value="@p"></div><div class="field"><label>Text</label><input id="tt" value="JMB HUB"></div><div class="field"><label>Type</label><select id="ty"><option>title</option><option>subtitle</option><option>actionbar</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/title '+document.querySelector('#tp').value+' '+document.querySelector('#ty').value+' {"text":"'+document.querySelector('#tt').value.replace(/"/g,'')+'"}')}
function tellraw(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="trp" value="@a"></div><div class="field"><label>Message</label><input id="trm" value="Welcome to JMB HUB!"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/tellraw '+document.querySelector('#trp').value+' {"text":"'+document.querySelector('#trm').value.replace(/"/g,'')+'","color":"aqua"}')}
function particle(){panel('<div class="form-grid"><div class="field"><label>Particle</label><input id="pa" value="minecraft:happy_villager"></div><div class="field"><label>Position</label><input id="pp" value="~ ~1 ~"></div><div class="field"><label>Count</label><input id="pc" type="number" value="20"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/particle '+document.querySelector('#pa').value+' '+document.querySelector('#pp').value+' 0 0 0 0.1 '+document.querySelector('#pc').value)}
function execute(){panel('<div class="form-grid"><div class="field"><label>Target</label><input id="ex" value="@p"></div><div class="field"><label>Command</label><input id="ec" value="say Hello JMB"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/execute as '+document.querySelector('#ex').value+' at @s run '+document.querySelector('#ec').value.replace(/^\//,''))}
function setblock(){panel('<div class="form-grid"><div class="field"><label>Position</label><input id="sp" value="~ ~ ~"></div><div class="field"><label>Block</label><input id="sb" value="minecraft:stone"></div><div class="field"><label>Mode</label><select id="sm"><option>replace</option><option>destroy</option><option>keep</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/setblock '+document.querySelector('#sp').value+' '+document.querySelector('#sb').value+' '+document.querySelector('#sm').value)}
function scoreboard(){panel('<div class="form-grid"><div class="field"><label>Objective</label><input id="so" value="jmb"></div><div class="field"><label>Display name</label><input id="sd" value="JMB Score"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/scoreboard objectives add '+document.querySelector('#so').value+' dummy "'+document.querySelector('#sd').value.replace(/"/g,'')+'"')}
function worldborder(){panel('<div class="form-grid"><div class="field"><label>Size</label><input id="ws" type="number" value="1000"></div><div class="field"><label>X</label><input id="wx" value="0"></div><div class="field"><label>Z</label><input id="wz" value="0"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/worldborder set '+document.querySelector('#ws').value+'\n/worldborder center '+document.querySelector('#wx').value+' '+document.querySelector('#wz').value)}
function locate(){panel('<div class="field"><label>Structure</label><input id="ls" value="minecraft:village"></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/locate structure '+document.querySelector('#ls').value)}

function simpleCommand(label,cmd){panel('<div class="field"><label>'+label+'</label><input id="simpleValue" value="@p"></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output(cmd.replaceAll('{v}',document.querySelector('#simpleValue').value||'@p'))}
function advancement(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="ap" value="@p"></div><div class="field"><label>Advancement</label><input id="aa" value="minecraft:story/mine_stone"></div><div class="field"><label>Action</label><select id="ax"><option>grant</option><option>revoke</option></select></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/advancement '+document.querySelector('#ax').value+' '+document.querySelector('#ap').value+' only '+document.querySelector('#aa').value)}
function clear(){simpleCommand('Player','/clear {v}')}
function kick(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="kv" value="@p"></div><div class="field"><label>Reason</label><input id="kr" value="Please follow the server rules"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/kick '+document.querySelector('#kv').value+' '+document.querySelector('#kr').value)}
function ban(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="bv" value="PlayerName"></div><div class="field"><label>Reason</label><input id="br" value="Rule violation"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/ban '+document.querySelector('#bv').value+' '+document.querySelector('#br').value)}
function whitelist(){simpleCommand('Player','/whitelist add {v}')}
function spawnpoint(){panel('<div class="form-grid"><div class="field"><label>Player</label><input id="sv" value="@p"></div><div class="field"><label>Position</label><input id="spv" value="~ ~ ~"></div></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/spawnpoint '+document.querySelector('#sv').value+' '+document.querySelector('#spv').value)}
function setworldspawn(){panel('<div class="field"><label>Position</label><input id="swv" value="~ ~ ~"></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/setworldspawn '+document.querySelector('#swv').value)}
function difficulty(){panel('<div class="field"><label>Difficulty</label><select id="dv"><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></div>'+common());document.querySelector('#mcGenerate').onclick=()=>output('/difficulty '+document.querySelector('#dv').value)}
const mcExtended={item,kit,enchant,potion,teleport,effect,gamerule,time,summon,fill,give,clone,title,tellraw,particle,execute,setblock,scoreboard,worldborder,locate,advancement,clear,kick,ban,whitelist,spawnpoint,setworldspawn,difficulty};
function renderExtended(){library.innerHTML=tools.map(([id,i,n,d])=>'<button class="mc-choice" data-mc="'+id+'"><div class="mc-art">'+i+'</div><h3>'+n+'</h3><p>'+d+'</p><span class="pill">Open →</span></button>').join('');library.querySelectorAll('[data-mc]').forEach(b=>b.onclick=()=>openExtended(b.dataset.mc))}
function openExtended(id){head(id);mcExtended[id]();}
await guard();renderExtended();openExtended('item');
