import {APP_CONFIG} from '../config/app-config.js';
import {guard} from '../core/auth-guard.js';
import {app,db,backendReady} from '../core/firebase.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js';
import {collection,getDocs,query,orderBy,limit,doc,updateDoc,serverTimestamp,arrayUnion,setDoc,getDoc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {toast,esc} from '../core/ui.js';

const u=await guard();
if(!u.admin){location.replace('dashboard.html');throw new Error('Admin access denied')}
const owner=u.owner;
const gate=document.querySelector('#ownerGate');gate.textContent=owner?'Owner access recognized — full console enabled.':'Admin access recognized — support console enabled.';gate.className='notice online';
document.querySelector('#adminRole').textContent=owner?'Owner':'Admin';
document.querySelector('[data-owner-tab]')?.classList.toggle('hide',!owner);

async function loadTickets(){
 if(!backendReady){document.querySelector('#adminTicketRows').innerHTML='<tr><td colspan="6" class="empty">Firebase is unavailable.</td></tr>';return}
 try{const snap=await getDocs(query(collection(db,'tickets'),orderBy('createdAt','desc'),limit(100)));document.querySelector('#ticketCount').textContent=snap.docs.filter(d=>(d.data().status||'open')!=='closed').length;document.querySelector('#adminTicketRows').innerHTML=snap.empty?'<tr><td colspan="6" class="empty">No tickets yet.</td></tr>':snap.docs.map(d=>{const x=d.data();return '<tr><td>'+esc(d.id.slice(0,8))+'</td><td>'+esc(x.email||x.uid||'User')+'</td><td>'+esc(x.subject||'')+'</td><td><span class="pill">'+esc(x.status||'open')+'</span></td><td>'+(x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'—')+'</td><td><button class="btn btn-ghost ticket-open" data-id="'+d.id+'">Open</button></td></tr>'}).join('');document.querySelectorAll('.ticket-open').forEach(b=>b.onclick=()=>openTicket(b.dataset.id,snap.docs.find(d=>d.id===b.dataset.id)))}catch(e){document.querySelector('#adminTicketRows').innerHTML='<tr><td colspan="6" class="empty">Could not load tickets: '+esc(e.message)+'</td></tr>'}
}
async function openTicket(id,snapDoc){const x=snapDoc.data(),modal=document.querySelector('#adminModal'),body=document.querySelector('#modalBody');document.querySelector('#modalTitle').textContent=x.subject||'Support ticket';body.innerHTML='<div class="notice"><b>'+esc(x.email||'User')+'</b><br>'+esc(x.message||'')+'</div><div class="form-grid" style="margin-top:12px"><div class="field"><label>Status</label><select id="ticketStatus"><option value="open">Open</option><option value="pending">Pending</option><option value="closed">Closed</option></select></div><div class="field"><label>Reply</label><input id="ticketReply" placeholder="Write a reply to the user"></div></div><div class="actions"><button class="btn btn-primary" id="saveTicket">Save Ticket</button></div>';$('#ticketStatus').value=x.status||'open';modal.classList.remove('hide');document.querySelector('#saveTicket').onclick=async()=>{try{const status=$('#ticketStatus').value,reply=$('#ticketReply').value.trim(),data={status,updatedAt:serverTimestamp(),updatedBy:u.uid};if(reply)data.replies=arrayUnion({from:u.email||'Admin',message:reply,createdAt:new Date().toISOString()});await updateDoc(doc(db,'tickets',id),data);modal.classList.add('hide');toast('Ticket updated','good');loadTickets()}catch(e){toast('Could not update ticket: '+e.message)}}}
async function loadSuggestions(){if(!backendReady)return;try{const snap=await getDocs(query(collection(db,'suggestions'),orderBy('createdAt','desc'),limit(100)));document.querySelector('#suggestionCount').textContent=snap.docs.filter(d=>(d.data().status||'new')==='new').length;document.querySelector('#suggestionRows').innerHTML=snap.empty?'<div class="empty">No suggestions yet.</div>':snap.docs.map(d=>{const x=d.data();return '<article class="card" style="margin-top:10px"><div class="section-title"><div><b>'+esc(x.email||'User')+'</b><p class="muted">'+(x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'—')+'</p></div><span class="pill">'+esc(x.status||'new')+'</span></div><p>'+esc(x.text||'')+'</p><button class="btn btn-ghost suggestion-done" data-id="'+d.id+'">Mark reviewed</button></article>'}).join('');document.querySelectorAll('.suggestion-done').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'suggestions',b.dataset.id),{status:'reviewed',reviewedBy:u.uid,reviewedAt:serverTimestamp()});loadSuggestions()})}catch(e){document.querySelector('#suggestionRows').innerHTML='<div class="notice">Could not load suggestions.</div>'}}
let cachedLogs=[];
async function loadLogs(){if(!backendReady)return;try{const snap=await getDocs(query(collection(db,'logs'),orderBy('createdAt','desc'),limit(250)));cachedLogs=snap.docs.map(d=>({id:d.id,...d.data()}));$('#logCount').textContent=cachedLogs.length;renderLogs()}catch(e){$('#logRows').innerHTML='<tr><td colspan="6" class="empty">Could not load logs: '+esc(e.message)+'</td></tr>'}}
function renderLogs(){const f=$('#logFilter').value,rows=f?cachedLogs.filter(x=>x.event===f):cachedLogs;$('#logRows').innerHTML=rows.length?rows.slice(0,150).map(x=>'<tr><td>'+esc(x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'—')+'</td><td>'+esc(x.uid||'')+'</td><td>'+esc(x.event||'')+'</td><td>'+esc(x.page||'')+'</td><td>'+esc(x.target||x.game||'')+'</td><td><span class="pill">'+esc(x.mode||'normal')+'</span></td></tr>').join(''):'<tr><td colspan="6" class="empty">No logs for this filter.</td></tr>'}
function replay(){const c=$('#replayCanvas'),ctx=c.getContext('2d'),points=cachedLogs.filter(x=>x.event==='pointer_click'&&Number.isFinite(x.x)&&Number.isFinite(x.y));let i=0;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#090d18';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='rgba(255,255,255,.07)';for(let x=0;x<c.width;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,c.height);ctx.stroke()}for(let y=0;y<c.height;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke()}if(!points.length){$('#replayStatus').textContent='No extreme click points found. Set Extreme mode first.';return}$('#replayStatus').textContent='Replaying '+points.length+' normalized click points — visual map only.';const step=()=>{if(i>=points.length){return}const p=points[i++];const x=p.x*c.width,y=p.y*c.height;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fillStyle='rgba(124,92,255,.8)';ctx.fill();ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.strokeStyle='rgba(0,212,255,.3)';ctx.stroke();setTimeout(step,Math.max(25,Math.min(180,(points[i]?.at||p.at)-p.at||60)))};step()}
async function loadUsers(){if(!owner){$('#userRows').innerHTML='<tr><td colspan="6" class="empty">Account list is owner-only.</td></tr>';return}try{if(!app){throw Error('Firebase app unavailable')}const fn=getFunctions(app,'asia-south1'),call=httpsCallable(fn,'listUsers'),res=await call({});const users=res.data.users||[];$('#userCount').textContent=users.length;$('#userRows').innerHTML=users.map(x=>'<tr><td>'+esc(x.email||'—')+'</td><td>'+esc(x.displayName||'—')+'</td><td>'+(x.emailVerified?'✓':'—')+'</td><td>'+esc(x.lastSignInAt?new Date(x.lastSignInAt).toLocaleString():'—')+'</td><td><span class="pill">'+esc(x.admin?'Admin':'Member')+'</span></td><td>'+(x.uid===u.uid?'<span class="pill">Owner</span>':'<button class="btn btn-ghost role-btn" data-uid="'+esc(x.uid)+'" data-role="'+(x.admin?'member':'admin')+'">'+(x.admin?'Remove admin':'Make admin')+'</button>')+'</td></tr>').join('');document.querySelectorAll('.role-btn').forEach(b=>b.onclick=()=>setRole(b.dataset.uid,b.dataset.role))}catch(e){$('#userRows').innerHTML='<tr><td colspan="6" class="empty">Account function is not deployed yet: '+esc(e.message)+'</td></tr>'}}
async function setRole(uid,role){if(!owner)return;try{const fn=getFunctions(app,'asia-south1');await httpsCallable(fn,'setUserRole')({uid,role});toast('Role updated. User must sign in again.','good');loadUsers()}catch(e){toast('Could not change role: '+e.message)}}
async function loadTelemetry(){if(!owner||!backendReady)return;try{const s=await getDoc(doc(db,'settings','telemetry'));if(s.exists()&&['low','normal','extreme'].includes(s.data().mode))$('#telemetryMode').value=s.data().mode}catch{}}
async function saveTelemetry(){if(!owner)return;const mode=$('#telemetryMode').value;try{await setDoc(doc(db,'settings','telemetry'),{mode,updatedBy:u.uid,updatedAt:serverTimestamp()},{merge:true});sessionStorage.setItem('jmb-telemetry-mode',mode);toast('Logging mode saved','good')}catch(e){toast('Could not save logging mode: '+e.message)}}
function setupTabs(){document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{const tab=b.dataset.tab;document.querySelectorAll('.admin-section').forEach(s=>s.classList.add('hide'));document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('btn-primary'));b.classList.add('btn-primary');const map={tickets:'#adminTickets',suggestions:'#adminSuggestions',logs:'#adminLogs',users:'#adminUsers',services:'#adminServices',security:'#adminSecurity'};if(map[tab]&&((tab!=='services'&&tab!=='security')||owner))document.querySelector(map[tab]).classList.remove('hide');if(tab==='logs')loadLogs();if(tab==='users')loadUsers();if(tab==='security')loadTelemetry()})}
function setupServices(){const saved=JSON.parse(localStorage.getItem('jmb-service-settings')||'{}');document.querySelectorAll('.service-select').forEach(x=>{if(saved[x.dataset.key]?.enabled===false)x.value='off'});document.querySelectorAll('.service-message').forEach(x=>{if(saved[x.dataset.key]?.message)x.value=saved[x.dataset.key].message});$('#save')?.addEventListener('click',async()=>{const services={};document.querySelectorAll('.service-select').forEach(s=>{const k=s.dataset.key;services[k]={enabled:s.value==='on',message:document.querySelector('.service-message[data-key="'+k+'"]').value}});localStorage.setItem('jmb-service-settings',JSON.stringify(services));try{await setDoc(doc(db,'settings','portal'),{services,updatedBy:u.uid,updatedAt:serverTimestamp()},{merge:true});toast('Service settings saved','good')}catch(e){toast('Could not save service settings: '+e.message)}})}
const $=s=>document.querySelector(s);
$('#closeModal').onclick=()=>$('#adminModal').classList.add('hide');$('#adminModal').addEventListener('click',e=>{if(e.target.id==='adminModal')e.currentTarget.classList.add('hide')});
$('#refreshTickets').onclick=loadTickets;$('#refreshSuggestions').onclick=loadSuggestions;$('#refreshLogs').onclick=loadLogs;$('#logFilter').onchange=renderLogs;$('#replayLogs').onclick=replay;$('#refreshUsers').onclick=loadUsers;$('#saveTelemetry').onclick=saveTelemetry;
setupTabs();setupServices();loadTickets();loadSuggestions();