import {db,backendReady,functions} from '../core/firebase.js';
import {guard} from '../core/auth-guard.js';
import {collection,query,orderBy,limitToLast,onSnapshot,deleteDoc,doc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {httpsCallable} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js';
const list=document.querySelector('#chatList'),form=document.querySelector('#chatForm'),input=document.querySelector('#chatInput'),status=document.querySelector('#chatStatus');
let user=null;
const clean=s=>String(s||'').replace(/[<>]/g,'').trim().slice(0,500);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(s){const d=s.data(),r=document.createElement('article');r.className='chat-message';const name=esc(d.displayName||'JMB User'),role=['Owner','Admin','Member'].includes(d.role)?d.role:'Member';const t=d.createdAt?.toDate?.()?.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})||'now';r.innerHTML=`<div class="chat-avatar">${esc((d.displayName||'J')[0].toUpperCase())}</div><div class="chat-bubble"><div class="chat-meta"><strong>${name}</strong><span class="chat-role ${role.toLowerCase()}">${role}</span><time>${t}</time>${user?.owner||user?.admin?`<button class="chat-delete" data-id="${s.id}" aria-label="Delete message">×</button>`:''}</div><p>${esc(d.text)}</p></div>`;if(user?.owner||user?.admin)r.querySelector('.chat-delete').onclick=async()=>{try{await deleteDoc(doc(db,'globalChat',s.id))}catch{status.textContent='That message could not be removed.'}};return r}
async function boot(){user=await guard();if(!backendReady||!db||!functions){status.textContent='Chat is unavailable right now.';form.classList.add('hide');return}const q=query(collection(db,'globalChat'),orderBy('createdAt','asc'),limitToLast(100));onSnapshot(q,snap=>{list.innerHTML='';snap.forEach(s=>list.appendChild(render(s)));list.scrollTop=list.scrollHeight;status.textContent=`${snap.size} recent messages`;},()=>status.textContent='Could not load chat right now.');const send=httpsCallable(functions,'sendGlobalChat');form.onsubmit=async e=>{e.preventDefault();const text=clean(input.value);if(!text)return;input.disabled=true;try{await send({text});input.value='';}catch(err){status.textContent=err?.message?.replace('FirebaseError: ','')||'Message could not be sent.'}finally{input.disabled=false;input.focus()}}}
boot();
