import {auth,firebaseEnabled} from '../core/firebase.js'; import {APP_CONFIG} from '../config/app-config.js'; import {$,toast} from '../core/ui.js'; import {GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendPasswordResetEmail,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
const modeBtn=$('#modeBtn'),modeText=$('#modeText'),submit=$('#submitBtn'),error=$('#authError'),email=$('#email'),password=$('#password'); let signup=false;
function showError(e){error.textContent=e?.message?.replace(/^Firebase:\s*/,'')||String(e);error.classList.remove('hide')}
function requireFirebase(){if(!firebaseEnabled){showError('Demo mode is active. Add your Firebase Web App config first to enable real authentication.');return false}return true}
if(firebaseEnabled){onAuthStateChanged(auth,u=>{if(u)location.href='dashboard.html'})}
$('#googleBtn').onclick=async()=>{if(!requireFirebase())return;try{await signInWithPopup(auth,new GoogleAuthProvider());location.href='dashboard.html'}catch(e){showError(e)}};
$('#discordBtn').onclick=()=>{if(!APP_CONFIG.DISCORD_OAUTH_URL){showError('Discord login is not configured yet. Set DISCORD_OAUTH_URL to your secure OAuth backend.');return}location.href=APP_CONFIG.DISCORD_OAUTH_URL};
modeBtn.onclick=()=>{signup=!signup;submit.textContent=signup?'Create Account →':'Sign In →';modeText.textContent=signup?'Already have an account?':'New to JMB Portal?';modeBtn.textContent=signup?'Sign in':'Create account';$('#authSub').textContent=signup?'Create your JMB Portal account.':'Sign in to open your dashboard.';error.classList.add('hide')};
submit.onclick=async()=>{error.classList.add('hide');if(!requireFirebase())return;const e=email.value.trim(),p=password.value;if(!e||!p)return showError('Enter your email and password.');try{if(signup)await createUserWithEmailAndPassword(auth,e,p);else await signInWithEmailAndPassword(auth,e,p);location.href='dashboard.html'}catch(err){showError(err)}};
$('#forgotBtn').onclick=async()=>{if(!requireFirebase())return;const e=email.value.trim();if(!e)return showError('Enter your email first.');try{await sendPasswordResetEmail(auth,e);toast('Password reset email sent','good')}catch(err){showError(err)}};
