import {guard} from '../core/auth-guard.js';
import {db,backendReady} from '../core/firebase.js';
import {collection,query,orderBy,limit,getDocs,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {$,toast} from '../core/ui.js';
import {openWorkspace} from '../core/workspace-window.js';

let user,current='snake',sessionScore=0;
const stage=$('#gameStage'),library=$('#gameLibrary');
const games=[
 ['snake','🐍','Snake','Classic snake with touch + arrow controls.'],
 ['click','⚡','Click Rush','Tap as fast as possible for 10 seconds.'],
 ['reaction','🟢','Reaction','Test how quickly you can react.'],
 ['target','🎯','Target Tap','Hit moving targets before time runs out.'],
 ['dodge','💫','Dodge Blocks','Move around and avoid incoming blocks.'],
 ['tap','🥁','Tap Tempo','Tap the beat and build a streak.'],
 ['number','🔢','Number Guess','Find the hidden number in fewer tries.'],
 ['math','🧠','Math Sprint','Solve quick math questions for points.'],
 ['color','🎨','Color Match','Tap the color that matches the word.'],
 ['whack','🔨','Whack-a-Mole','Tap the active mole before it moves.'],
 ['memory','🃏','Memory Match','Match every pair with your memory.'],
 ['tic','⭕','Tic-Tac-Toe','Play a quick solo game against the computer.'],
 ['stack','🧱','Stack Drop','Drop blocks and build the tallest tower.'],
 ['coin','🪙','Coin Catch','Move and collect coins for 20 seconds.'],
 ['flappy','🐤','Flappy Dot','Tap to fly through the gaps.'],
 ['2048','🔢','2048 Mini','Merge numbers and chase a high score.'],
 ['rps','✊','Rock Paper Scissors','Play quick rounds against the computer.'],
 ['coinflip','🪙','Coin Flip','Pick heads or tails and test your luck.'],
 ['higher','📈','Higher or Lower','Guess whether the next number is higher.'],
 ['word','🔤','Word Scramble','Unscramble a short word as fast as you can.'],
 ['aim','🎯','Aim Trainer','Tap targets quickly and improve your reaction.'],
 ['simon','🟣','Simon Lights','Repeat the growing color sequence.'],
 ['pong','🏓','Mini Pong','Keep the ball alive with the mobile paddle.'],
 ['lights','💡','Lights Out','Turn every light off in as few moves as possible.'],
 ['connect','🔴','Connect Four','Drop pieces and connect four.'],
 ['reaction2','⚡','Speed Tap','Tap the target 20 times as fast as possible.'],
 ['guesscolor','🌈','Color Guess','Guess the hidden color from clues.'],
 ['jmbdash','🟪','JMB Dash','Original rhythm runner with tap-to-jump controls.'],
 ['quickdraw','🔫','Quick Draw','Wait for GO, then tap as fast as you can.'],
 ['maze','🧩','Maze Escape','Find the exit using touch-friendly controls.'],
 ['typing','⌨️','Typing Rush','Type the shown word before the timer ends.'],
 ['dice','🎲','Dice Duel','Roll against the computer and collect wins.'],
 ['oddone','🔎','Odd One Out','Find the tile that is different.'],
 ['colormemory','🧠','Color Memory','Remember the highlighted tile and repeat it.'],
 ['safegrid','🛡️','Safe Grid','Cross the grid without hitting hidden traps.']
];
function safe(v){return String(v).replace(/[<>]/g,'')}
function renderLibrary(){library.innerHTML=games.map(([id,icon,title,desc])=>`<button class="game-card" data-game="${id}"><div class="game-art">${icon}</div><h3>${title}</h3><p>${desc}</p><span class="pill">Play →</span></button>`).join('');library.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>switchGame(b.dataset.game))}
function setHeader(g){const x=games.find(a=>a[0]===g);$('#activeGameTitle').textContent=x[2];$('#activeGameDesc').textContent=x[3];$('#lbTitle').textContent=x[2];library.querySelectorAll('.game-card').forEach(b=>b.classList.toggle('active',b.dataset.game===g))}
async function saveScore(game,score){score=Math.max(0,Math.floor(Number(score)||0));sessionScore+=score;$('#overallScore').textContent=sessionScore;if(!backendReady||user?.demo||score<=0)return;try{await addDoc(collection(db,'leaderboards',game,'scores'),{uid:user.uid,player:user.displayName||user.email?.split('@')[0]||'Player',score,createdAt:serverTimestamp()});await loadBoard(game)}catch(e){toast('Score could not be saved: '+e.message)}}
async function loadBoard(game){if(!backendReady){$('#leaderboardBody').innerHTML='<tr><td colspan="3" class="empty">Online leaderboard is temporarily unavailable.</td></tr>';return}try{const snap=await getDocs(query(collection(db,'leaderboards',game,'scores'),orderBy('score','desc'),limit(20)));$('#leaderboardBody').innerHTML=snap.empty?'<tr><td colspan="3" class="empty">No scores yet.</td></tr>':snap.docs.map((d,i)=>{const x=d.data();return `<tr><td>${i+1}</td><td>${safe(x.player||'Player')}</td><td>${Number(x.score||0)}</td></tr>`}).join('')}catch{$('#leaderboardBody').innerHTML='<tr><td colspan="3" class="empty">Leaderboard unavailable right now.</td></tr>'}}

function snake(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🐍 Snake</h2><div class="score-readout">Score: <b id="snakeScore">0</b></div><canvas id="snakeCanvas" width="320" height="320" style="max-width:100%;border:1px solid var(--line);border-radius:18px;background:#090d17;margin:14px 0;touch-action:none"></canvas><div class="dpad"><button class="up" data-d="up">▲</button><button class="left" data-d="left">◀</button><button class="down" data-d="down">▼</button><button class="right" data-d="right">▶</button></div><button class="btn btn-primary" id="snakeStart">Start / Restart</button><p class="muted">Use the arrows, keyboard or swipe on the board.</p></div>';
const c=$('#snakeCanvas'),ctx=c.getContext('2d'),size=20,cell=16;let timer,body,dir,food,score=0,started=false;
function reset(){body=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];dir={x:1,y:0};food={x:4+Math.floor(Math.random()*16),y:4+Math.floor(Math.random()*16)};score=0;$('#snakeScore').textContent=0;draw()}
function draw(){ctx.clearRect(0,0,320,320);ctx.fillStyle='#10182a';ctx.fillRect(0,0,320,320);ctx.fillStyle='#7c5cff';body.forEach(s=>ctx.fillRect(s.x*cell+2,s.y*cell+2,12,12));ctx.fillStyle='#35e6a2';ctx.fillRect(food.x*cell+3,food.y*cell+3,10,10)}
function setDir(d){if(d==='up'&&dir.y!==1)dir={x:0,y:-1};if(d==='down'&&dir.y!==-1)dir={x:0,y:1};if(d==='left'&&dir.x!==1)dir={x:-1,y:0};if(d==='right'&&dir.x!==-1)dir={x:1,y:0}}
function step(){const h={x:body[0].x+dir.x,y:body[0].y+dir.y};if(h.x<0||h.x>=size||h.y<0||h.y>=size||body.some(s=>s.x===h.x&&s.y===h.y)){clearInterval(timer);started=false;toast(`Snake over — ${score}`);saveScore('snake',score);return}body.unshift(h);if(h.x===food.x&&h.y===food.y){score++;$('#snakeScore').textContent=score;do{food={x:Math.floor(Math.random()*size),y:Math.floor(Math.random()*size)}}while(body.some(s=>s.x===food.x&&s.y===food.y))}else body.pop();draw()}
function start(){clearInterval(timer);reset();started=true;timer=setInterval(step,100)}
$('#snakeStart').onclick=start;document.querySelectorAll('.dpad [data-d]').forEach(b=>b.onpointerdown=()=>setDir(b.dataset.d));window.addEventListener('keydown',e=>{if(current!=='snake'||!started)return;({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key])&&setDir(({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key]))});let last; c.addEventListener('touchstart',e=>{last=e.touches[0]},{passive:true});c.addEventListener('touchend',e=>{if(!last)return;const t=e.changedTouches[0],dx=t.clientX-last.clientX,dy=t.clientY-last.clientY;if(Math.max(Math.abs(dx),Math.abs(dy))>25)setDir(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));last=null},{passive:true});reset()}

function clickRush(){stage.innerHTML='<div class="game-view"><h2 class="game-title">⚡ Click Rush</h2><p class="muted">Tap the button as many times as you can.</p><div id="clickTimer" class="big-number">10</div><button class="btn btn-primary game-btn" id="rushBtn">START</button><p class="score-readout">Clicks: <b id="clickScore">0</b></p></div>';let active=false,score=0;const btn=$('#rushBtn');btn.onclick=()=>{if(active)return;active=true;score=0;$('#clickScore').textContent=0;btn.textContent='TAP!';let t=10;const iv=setInterval(()=>{t--;$('#clickTimer').textContent=t;if(t<=0){clearInterval(iv);active=false;btn.textContent='START AGAIN';toast(`Click Rush — ${score}`);saveScore('click',score)}},1000)};btn.onpointerdown=e=>{if(active){e.preventDefault();score++;$('#clickScore').textContent=score}}}

function reaction(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🟢 Reaction</h2><p class="muted">Tap when the panel turns green.</p><div class="reaction-box" id="reactionBox">Tap to start</div><div class="score-readout" id="reactionReadout" style="margin-top:12px">—</div></div>';const box=$('#reactionBox'),read=$('#reactionReadout');let start=0,timer;box.onclick=()=>{if(box.classList.contains('go')){const ms=Date.now()-start;read.textContent=`${ms} ms`;box.classList.remove('go');box.textContent='Tap to try again';saveScore('reaction',Math.max(1,1000-ms));return}box.textContent='Wait…';clearTimeout(timer);timer=setTimeout(()=>{box.classList.add('go');box.textContent='TAP!';start=Date.now()},900+Math.random()*2200)}}

function target(){stage.innerHTML='<div class="game-view"><div class="section-title"><div><h2 class="game-title">🎯 Target Tap</h2><p class="muted">Hit targets for 20 seconds.</p></div><div class="score-readout">Score: <b id="targetScore">0</b></div></div><div class="target-stage" id="targetStage"><button class="btn btn-primary" id="targetStart">START</button></div></div>';const s=$('#targetStage'),start=$('#targetStart'),scoreEl=$('#targetScore');let score=0,active=false,iv,end;function spawn(){const t=document.createElement('button');t.className='target';t.style.left=Math.random()*Math.max(1,s.clientWidth-60)+'px';t.style.top=Math.random()*Math.max(1,s.clientHeight-60)+'px';t.onclick=()=>{if(!active)return;score++;scoreEl.textContent=score;t.remove();spawn()};s.append(t);setTimeout(()=>t.remove(),900)}start.onclick=()=>{if(active)return;active=true;score=0;scoreEl.textContent=0;start.remove();for(let i=0;i<2;i++)spawn();end=Date.now()+20000;iv=setInterval(()=>{spawn();if(Date.now()>end){clearInterval(iv);active=false;s.querySelectorAll('.target').forEach(x=>x.remove());toast(`Target Tap — ${score}`);saveScore('target',score)}},700)}}

function dodge(){stage.innerHTML='<div class="game-view"><h2 class="game-title">💫 Dodge Blocks</h2><p class="muted">Move the green player and survive for 20 seconds.</p><div class="dodge-stage" id="dodgeStage"><div class="dodge-player" id="dodgePlayer"></div></div><button class="btn btn-primary" id="dodgeStart">START</button><p class="score-readout">Survival score: <b id="dodgeScore">0</b></p></div>';const s=$('#dodgeStage'),p=$('#dodgePlayer'),b=$('#dodgeStart');let x=50,y=240,active=false,keys={},iv,score=0;function move(){x=Math.max(0,Math.min(s.clientWidth-28,x+(keys.ArrowRight?5:0)-(keys.ArrowLeft?5:0)));y=Math.max(0,Math.min(s.clientHeight-28,y+(keys.ArrowDown?5:0)-(keys.ArrowUp?5:0)));p.style.left=x+'px';p.style.top=y+'px'}window.addEventListener('keydown',e=>{if(current==='dodge')keys[e.key]=true});window.addEventListener('keyup',e=>{if(current==='dodge')keys[e.key]=false});b.onclick=()=>{if(active)return;active=true;score=0;x=50;y=s.clientHeight-55;b.remove();const start=Date.now();iv=setInterval(()=>{move();if(Math.random()<.18){const e=document.createElement('div');e.className='dodge-enemy';e.style.left=Math.random()*Math.max(1,s.clientWidth-24)+'px';e.style.top='-30px';s.append(e);const fall=setInterval(()=>{e.style.top=(parseFloat(e.style.top)+4)+'px';const a=e.getBoundingClientRect(),q=p.getBoundingClientRect();if(a.left<q.right&&a.right>q.left&&a.top<q.bottom&&a.bottom>q.top){clearInterval(fall);clearInterval(iv);active=false;toast(`Dodge over — ${score}`);saveScore('dodge',score);e.remove()}if(parseFloat(e.style.top)>s.clientHeight){clearInterval(fall);e.remove()}},35)}score=Math.floor((Date.now()-start)/1000);$('#dodgeScore').textContent=score;if(score>=20){clearInterval(iv);active=false;toast('20 seconds survived!');saveScore('dodge',score*10)}},30)}}

function tap(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🥁 Tap Tempo</h2><p class="muted">Tap steadily for 15 seconds and keep your streak alive.</p><button class="btn btn-primary game-btn" id="tempo">START</button><div class="big-number" id="tempoScore">0</div></div>';const b=$('#tempo'),out=$('#tempoScore');let active=false,last=0,score=0,end; b.onclick=()=>{const now=Date.now();if(!active){active=true;score=0;last=now;end=now+15000;b.textContent='TAP!';out.textContent=0;return}if(now>end){active=false;b.textContent='START AGAIN';saveScore('tap',score);return}const gap=now-last;last=now;score+=Math.max(1,Math.round(100-Math.min(99,Math.abs(gap-500)/5)));out.textContent=score}}

function number(){const n=Math.floor(Math.random()*50)+1;stage.innerHTML=`<div class="game-view"><h2 class="game-title">🔢 Number Guess</h2><p class="muted">Guess a number from 1–50.</p><div class="number-box">1 — 50</div><input id="guessInput" class="tool-input" type="number" min="1" max="50" placeholder="Your guess"><button class="btn btn-primary" id="guessBtn">Guess</button><p id="guessMsg" class="score-readout"></p></div>`;let tries=0;$('#guessBtn').onclick=()=>{const g=Number($('#guessInput').value);if(!g)return;tries++;if(g===n){$('#guessMsg').textContent=`Correct in ${tries} tries!`;saveScore('number',Math.max(10,100-tries*10));return}$('#guessMsg').textContent=g<n?'Too low ↑':'Too high ↓'}}

function math(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🧠 Math Sprint</h2><div class="big-number" id="mathScore">0</div><div class="number-box" id="mathQ"></div><input id="mathA" class="tool-input" type="number" placeholder="Answer"><button class="btn btn-primary" id="mathBtn">Submit</button><p class="muted">Solve 10 questions.</p></div>';let score=0,i=0,a;function next(){const x=Math.floor(Math.random()*20)+1,y=Math.floor(Math.random()*20)+1;a=x+y;$('#mathQ').textContent=`${x} + ${y} = ?`;$('#mathA').value=''}next();$('#mathBtn').onclick=()=>{if(Number($('#mathA').value)===a)score+=10;i++;$('#mathScore').textContent=score;if(i>=10){toast(`Math Sprint — ${score}`);saveScore('math',score);return}next()}}

function color(){const colors=[['RED','#d44'],['BLUE','#4b8'],['GREEN','#56d'],['YELLOW','#e0b83d']];stage.innerHTML='<div class="game-view"><h2 class="game-title">🎨 Color Match</h2><p class="muted">Tap the button matching the word.</p><h2 id="colorWord"></h2><div class="color-pad" id="colorPad"></div><p>Score: <b id="colorScore">0</b></p></div>';let score=0;function next(){const target=colors[Math.floor(Math.random()*colors.length)];$('#colorWord').textContent=target[0];$('#colorPad').innerHTML=colors.map(c=>`<button style="background:${c[1]}" data-c="${c[0]}">${c[0]}</button>`).join('');$('#colorPad').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.c===target[0])score+=10;else score=Math.max(0,score-3);$('#colorScore').textContent=score;next()})}next();setTimeout(()=>saveScore('color',score),15000)}

function whack(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🔨 Whack-a-Mole</h2><p class="muted">Tap the active mole for 15 seconds.</p><div class="whack-grid" id="whackGrid"></div><p>Score: <b id="whackScore">0</b></p></div>';const g=$('#whackGrid');g.innerHTML=Array.from({length:9},(_,i)=>`<button class="mole" data-i="${i}">●</button>`).join('');let score=0;const iv=setInterval(()=>{g.querySelectorAll('.mole').forEach(x=>x.classList.remove('active'));g.children[Math.floor(Math.random()*9)].classList.add('active')},650);g.onclick=e=>{if(e.target.classList.contains('active')){score++;e.target.classList.remove('active');$('#whackScore').textContent=score}};setTimeout(()=>{clearInterval(iv);saveScore('whack',score);toast(`Whack-a-Mole — ${score}`)},15000)}

function memory(){const vals=['🍎','🚀','🐼','⭐','🎮','🌙','🍕','⚡'];let arr=[...vals,...vals].sort(()=>Math.random()-.5);stage.innerHTML='<div class="game-view"><h2 class="game-title">🃏 Memory Match</h2><div class="memory-grid" id="memoryGrid"></div><p>Moves: <b id="memMoves">0</b></p></div>';const g=$('#memoryGrid');g.innerHTML=arr.map((v,i)=>`<button data-v="${v}" data-i="${i}">${v}</button>`).join('');let open=[],matched=0,moves=0;g.onclick=e=>{const b=e.target;if(b.tagName!=='BUTTON'||b.classList.contains('revealed')||open.length===2)return;b.classList.add('revealed');open.push(b);if(open.length===2){moves++;$('#memMoves').textContent=moves;if(open[0].dataset.v===open[1].dataset.v){matched+=2;open=[];if(matched===arr.length){toast('Memory complete!');saveScore('memory',Math.max(10,200-moves*5))}}else setTimeout(()=>{open.forEach(x=>x.classList.remove('revealed'));open=[]},500)}}}

function tic(){stage.innerHTML='<div class="game-view"><h2 class="game-title">⭕ Tic-Tac-Toe</h2><div class="tic-grid" id="ticGrid"></div><p id="ticMsg" class="score-readout">Your turn</p></div>';const g=$('#ticGrid');let board=Array(9).fill(''),over=false;g.innerHTML=board.map((_,i)=>`<button data-i="${i}"></button>`).join('');function win(p){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(i=>board[i]===p))}function ai(){const empty=board.map((v,i)=>v?null:i).filter(i=>i!==null);if(!empty.length)return;board[empty[Math.floor(Math.random()*empty.length)]]='O'}g.onclick=e=>{const i=Number(e.target.dataset.i);if(over||board[i])return;board[i]='X';e.target.textContent='X';if(win('X')){over=true;$('#ticMsg').textContent='You win!';saveScore('tic',100);return}ai();g.querySelectorAll('button').forEach((b,j)=>b.textContent=board[j]);if(win('O')){over=true;$('#ticMsg').textContent='Computer wins.';return}if(board.every(Boolean)){over=true;$('#ticMsg').textContent='Draw.'}}}

function stack(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🧱 Stack Drop</h2><p class="muted">Tap to drop the moving block.</p><div class="stack-stage" id="stackStage"></div><button class="btn btn-primary" id="stackBtn">START</button><p>Height: <b id="stackScore">0</b></p></div>';const s=$('#stackStage'),b=$('#stackBtn'),sc=$('#stackScore');let active=false,x=20,dir=1,y=230,height=0,iv;function spawn(){const q=document.createElement('div');q.className='stack-block';q.style.width=Math.max(40,120-height*3)+'px';q.style.left=x+'px';q.style.bottom=y+'px';s.append(q);return q}b.onclick=()=>{if(active)return;active=true;b.textContent='DROP';height=0;s.innerHTML='';let block=spawn();iv=setInterval(()=>{x+=dir*3;if(x<0||x>s.clientWidth-block.offsetWidth)dir*=-1;block.style.left=x+'px'},20);b.onclick=()=>{if(!active)return;clearInterval(iv);height++;sc.textContent=height;y=Math.max(25,y-23);block=spawn();iv=setInterval(()=>{x+=dir*3;if(x<0||x>s.clientWidth-block.offsetWidth)dir*=-1;block.style.left=x+'px'},20);if(height>=10){active=false;b.textContent='RESTART';toast('Tower complete!');saveScore('stack',height*10);b.onclick=()=>location.reload()}}}}

function coin(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🪙 Coin Catch</h2><p class="muted">Move the player and catch coins.</p><div class="dodge-stage" id="coinStage"><div class="dodge-player" id="coinPlayer"></div></div><p>Coins: <b id="coinScore">0</b></p></div>';const s=$('#coinStage'),p=$('#coinPlayer');let x=50,y=240,score=0,keys={};function move(){x=Math.max(0,Math.min(s.clientWidth-28,x+(keys.ArrowRight?6:0)-(keys.ArrowLeft?6:0)));y=Math.max(0,Math.min(s.clientHeight-28,y+(keys.ArrowDown?6:0)-(keys.ArrowUp?6:0)));p.style.left=x+'px';p.style.top=y+'px'}window.addEventListener('keydown',e=>{if(current==='coin')keys[e.key]=true});window.addEventListener('keyup',e=>{if(current==='coin')keys[e.key]=false});const iv=setInterval(()=>{move();const c=document.createElement('div');c.className='coin';c.style.left=Math.random()*Math.max(1,s.clientWidth-25)+'px';c.style.top='-25px';s.append(c);let t=setInterval(()=>{c.style.top=(parseFloat(c.style.top)+4)+'px';const a=c.getBoundingClientRect(),q=p.getBoundingClientRect();if(a.left<q.right&&a.right>q.left&&a.top<q.bottom&&a.bottom>q.top){score++;$('#coinScore').textContent=score;clearInterval(t);c.remove()}if(parseFloat(c.style.top)>s.clientHeight){clearInterval(t);c.remove()}},35)},600);setTimeout(()=>{clearInterval(iv);toast(`Coin Catch — ${score}`);saveScore('coin',score)},20000)}

function flappy(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🐤 Flappy Dot</h2><p class="muted">Tap to flap through the gaps.</p><div class="flappy-stage" id="flappyStage"><div class="flappy-bird" id="flappyBird"></div></div><button class="btn btn-primary" id="flappyStart">START</button><p>Score: <b id="flappyScore">0</b></p></div>';const s=$('#flappyStage'),p=$('#flappyBird'),b=$('#flappyStart');let y=140,vy=0,score=0,active=false,iv;function flap(){if(active)vy=-6}b.onclick=()=>{if(active)return;active=true;b.textContent='TAP TO FLAP';iv=setInterval(()=>{vy+=.35;y+=vy;p.style.top=y+'px';p.style.left='80px';if(y<0||y>s.clientHeight-25){clearInterval(iv);active=false;toast(`Flappy Dot — ${score}`);saveScore('flappy',score)}if(Math.random()<.025){const gap=70+Math.random()*130;const top=document.createElement('div'),bot=document.createElement('div');top.className=bot.className='pipe';top.style.left=bot.style.left=s.clientWidth+'px';top.style.top='0';top.style.height=gap+'px';bot.style.bottom='0';bot.style.height=(s.clientHeight-gap-95)+'px';s.append(top,bot);let x=s.clientWidth;const mv=setInterval(()=>{x-=3;top.style.left=bot.style.left=x+'px';if(x<40&&x>15)score++;if(x<-60){clearInterval(mv);top.remove();bot.remove()}},25)}$('#flappyScore').textContent=score},25);s.onpointerdown=flap};document.addEventListener('keydown',e=>{if(current==='flappy'&&e.code==='Space')flap()})}

function mini2048(){let board=Array(16).fill(0);stage.innerHTML='<div class="game-view"><h2 class="game-title">🔢 2048 Mini</h2><div class="four-grid" id="g2048"></div><p>Score: <b id="g2048Score">0</b></p><p class="muted">Swipe or use arrow keys.</p></div>';const g=$('#g2048'),sc=$('#g2048Score');let score=0;function draw(){g.innerHTML=board.map((v,i)=>`<button data-i="${i}">${v||''}</button>`).join('')}function add(){const e=board.map((v,i)=>v?null:i).filter(i=>i!==null);if(e.length)board[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4}function move(dir){let old=board.join(),rows=[];for(let r=0;r<4;r++){let line=dir==='left'||dir==='right'?[...board.slice(r*4,r*4+4)]:[board[r],board[r+4],board[r+8],board[r+12]];if(dir==='right'||dir==='down')line.reverse();line=line.filter(Boolean);for(let i=0;i<line.length-1;i++)if(line[i]===line[i+1]){line[i]*=2;score+=line[i];line.splice(i+1,1)}while(line.length<4)line.push(0);if(dir==='right'||dir==='down')line.reverse();rows.push(line)}if(dir==='left'||dir==='right')board=rows.flat();else board=Array.from({length:4},(_,i)=>rows.map(r=>r[i])).flat();if(board.join()!==old){add();sc.textContent=score;draw();if(Math.max(...board)>=128){toast('2048 milestone!');saveScore('2048',score)}}}draw();add();draw();window.addEventListener('keydown',e=>{if(current!=='2048')return;const d=({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key]);if(d)move(d)})}

function rps(){stage.innerHTML='<div class="game-view"><h2 class="game-title">✊ Rock Paper Scissors</h2><p class="muted">Choose your move.</p><div class="tool-actions" style="justify-content:center"><button class="btn btn-primary rps" data-v="rock">✊ Rock</button><button class="btn btn-primary rps" data-v="paper">✋ Paper</button><button class="btn btn-primary rps" data-v="scissors">✌️ Scissors</button></div><div id="rpsMsg" class="result-box">Ready!</div><p>Score: <b id="rpsScore">0</b></p></div>';let score=0;document.querySelectorAll('.rps').forEach(b=>b.onclick=()=>{const me=b.dataset.v,ai=['rock','paper','scissors'][Math.floor(Math.random()*3)];const win=me===ai?0:(me==='rock'&&ai==='scissors'||me==='paper'&&ai==='rock'||me==='scissors'&&ai==='paper')?1:-1;score+=win;$('#rpsScore').textContent=score;$('#rpsMsg').textContent=win===0?'Draw!':win>0?'You win — '+ai:'Computer wins — '+ai;if(Math.abs(score)>=3)saveScore('rps',Math.max(1,score+3))})}
function coinflip(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🪙 Coin Flip</h2><p class="muted">Pick a side.</p><div class="tool-actions" style="justify-content:center"><button class="btn btn-primary" id="heads">Heads</button><button class="btn btn-ghost" id="tails">Tails</button></div><div id="coinMsg" class="big-number">?</div></div>';let n=0;const flip=v=>{const out=Math.random()<.5?'heads':'tails';$('#coinMsg').textContent=out==='heads'?'🪙 HEADS':'🪙 TAILS';if(out===v){n++;toast('Correct!','good');saveScore('coinflip',n*10)}else toast('Try again')};$('#heads').onclick=()=>flip('heads');$('#tails').onclick=()=>flip('tails')}
function higher(){let cur=Math.floor(Math.random()*90)+10,score=0;stage.innerHTML='<div class="game-view"><h2 class="game-title">📈 Higher or Lower</h2><div class="big-number" id="higherNum"></div><p class="muted">Will the next number be higher or lower?</p><div class="tool-actions" style="justify-content:center"><button class="btn btn-primary" id="higher">Higher ↑</button><button class="btn btn-ghost" id="lower">Lower ↓</button></div><div id="higherMsg" class="result-box">Make your guess.</div></div>';$('#higherNum').textContent=cur;const play=guess=>{const next=Math.floor(Math.random()*90)+10;const ok=guess==='higher'?next>=cur:next<=cur;if(ok)score+=10;else{toast('Round over — '+score);saveScore('higher',score);score=0}$('#higherMsg').textContent=next+' — '+(ok?'Correct!':'Wrong!');cur=next;$('#higherNum').textContent=cur};$('#higher').onclick=()=>play('higher');$('#lower').onclick=()=>play('lower')}
function word(){const words=['minecraft','portal','gamer','pixel','rocket','dragon','castle','jmbhub'];const word=words[Math.floor(Math.random()*words.length)];const mix=word.split('').sort(()=>Math.random()-.5).join('');stage.innerHTML='<div class="game-view"><h2 class="game-title">🔤 Word Scramble</h2><div class="big-number" id="scramble"></div><input id="wordInput" class="tool-input" placeholder="Unscramble it"><button class="btn btn-primary" id="wordBtn">Check</button><div id="wordMsg" class="result-box">Good luck!</div></div>';$('#scramble').textContent=mix;$('#wordBtn').onclick=()=>{if($('#wordInput').value.trim().toLowerCase()===word){$('#wordMsg').textContent='Correct!';saveScore('word',50);setTimeout(word,500)}else $('#wordMsg').textContent='Not quite — try again.'}}
function aim(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🎯 Aim Trainer</h2><p class="muted">Tap 15 targets as quickly as possible.</p><div class="target-stage" id="aimStage"><button class="btn btn-primary" id="aimStart">START</button></div><div id="aimMsg" class="score-readout">Targets: 0 / 15</div></div>';const s=$('#aimStage');let n=0,start=0;function spawn(){const t=document.createElement('button');t.className='target';t.style.left=Math.random()*Math.max(1,s.clientWidth-54)+'px';t.style.top=Math.random()*Math.max(1,s.clientHeight-54)+'px';t.onclick=()=>{n++;t.remove();$('#aimMsg').textContent='Targets: '+n+' / 15';if(n>=15){const ms=Date.now()-start;toast('Aim time: '+ms+' ms');saveScore('aim',Math.max(1,Math.floor(15000/ms*100)))}else spawn()};s.append(t)}$('#aimStart').onclick=()=>{n=0;start=Date.now();$('#aimStart').remove();spawn()}}
function simon(){const colors=['red','blue','green','yellow'],seq=[];let pos=0;stage.innerHTML='<div class="game-view"><h2 class="game-title">🟣 Simon Lights</h2><p class="muted">Repeat the sequence.</p><div class="four-grid simon-grid">'+colors.map(x=>'<button data-c="'+x+'">'+x.toUpperCase()+'</button>').join('')+'</div><button class="btn btn-primary" id="simonStart">START</button><p id="simonMsg" class="score-readout">Level 0</p></div>';const msg=$('#simonMsg');function next(){seq.push(colors[Math.floor(Math.random()*4)]);pos=0;msg.textContent='Level '+seq.length;seq.forEach((x,i)=>setTimeout(()=>{const b=document.querySelector('[data-c="'+x+'"]');b.classList.add('active');setTimeout(()=>b.classList.remove('active'),220)},i*380))}$('#simonStart').onclick=next;document.querySelectorAll('.simon-grid button').forEach(b=>b.onclick=()=>{if(!seq.length)return;if(b.dataset.c!==seq[pos]){toast('Simon over — level '+(seq.length-1));saveScore('simon',Math.max(0,seq.length-1)*20);seq.length=0;pos=0;msg.textContent='Try again';return}pos++;if(pos===seq.length){saveScore('simon',seq.length*10);setTimeout(next,400)}})}
function pong(){stage.innerHTML='<div class="game-view"><h2 class="game-title">🏓 Mini Pong</h2><p class="muted">Drag your finger to control the paddle.</p><div class="pong-stage" id="pongStage"><div class="pong-paddle" id="pongPaddle"></div><div class="pong-ball" id="pongBall"></div></div><p>Score: <b id="pongScore">0</b></p></div>';const s=$('#pongStage'),p=$('#pongPaddle'),b=$('#pongBall');let y=120,by=100,bx=100,vy=2.7,vx=2.7,score=0;const move=e=>{const r=s.getBoundingClientRect(),cy=e.touches?e.touches[0].clientY:e.clientY;y=Math.max(0,Math.min(r.height-70,cy-r.top-35));p.style.top=y+'px'};s.addEventListener('pointermove',move);s.addEventListener('touchmove',move,{passive:true});const iv=setInterval(()=>{bx+=vx;by+=vy;if(by<0||by>s.clientHeight-18)vy*=-1;if(bx>s.clientWidth-18){vx=-Math.abs(vx);score++;$('#pongScore').textContent=score}if(bx<42&&by>y-12&&by<y+82)vx=Math.abs(vx);if(bx<0){clearInterval(iv);toast('Pong — '+score);saveScore('pong',score)}b.style.left=bx+'px';b.style.top=by+'px'},20)}
function lights(){let board=Array(25).fill(false);stage.innerHTML='<div class="game-view"><h2 class="game-title">💡 Lights Out</h2><p class="muted">Turn every light off.</p><div class="four-grid lights-grid" id="lightsGrid"></div><p>Moves: <b id="lightsMoves">0</b></p></div>';const g=$('#lightsGrid');let moves=0;function draw(){g.innerHTML=board.map((v,i)=>'<button class="'+(v?'active':'')+'" data-i="'+i+'">'+(v?'●':'·')+'</button>').join('')}function toggle(i){const x=i%5,y=Math.floor(i/5);[i,i-1,i+1,i-5,i+5].forEach(j=>{if(j>=0&&j<25&&Math.abs((j%5)-x)+Math.abs(Math.floor(j/5)-y)<=1)board[j]=!board[j]})}g.onclick=e=>{const i=Number(e.target.dataset.i);toggle(i);moves++;$('#lightsMoves').textContent=moves;draw();if(board.every(v=>!v)){toast('Lights Out complete!');saveScore('lights',Math.max(10,500-moves*10))}};for(let i=0;i<12;i++)toggle(Math.floor(Math.random()*25));draw()}
function connect(){let board=Array(42).fill(''),turn='R';stage.innerHTML='<div class="game-view"><h2 class="game-title">🔴 Connect Four</h2><div class="four-grid connect-grid" id="connectGrid"></div><p id="connectMsg">Your turn</p></div>';const g=$('#connectGrid');function draw(){g.innerHTML=board.map((v,i)=>'<button data-i="'+i+'" class="'+(v||'')+'">'+(v||'·')+'</button>').join('')}function win(v){for(let r=0;r<6;r++)for(let c=0;c<7;c++){const i=r*7+c;if(c<4&&[i,i+1,i+2,i+3].every(j=>board[j]===v))return true;if(r<3&&[i,i+7,i+14,i+21].every(j=>board[j]===v))return true}return false}g.onclick=e=>{let col=Number(e.target.dataset.i)%7;for(let r=5;r>=0;r--){const i=r*7+col;if(!board[i]){board[i]=turn;if(win(turn)){toast((turn==='R'?'You':'Computer')+' connected four!');if(turn==='R')saveScore('connect',100);turn='';draw();return}turn=turn==='R'?'Y':'R';break}}draw();if(turn==='Y'){const cols=[0,1,2,3,4,5,6].filter(c=>!board[c]);if(cols.length){const col=cols[Math.floor(Math.random()*cols.length)];for(let r=5;r>=0;r--){const i=r*7+col;if(!board[i]){board[i]='Y';break}}if(win('Y')){toast('Computer connected four!');turn=''}else turn='R';draw()}}};draw()}
function reaction2(){let n=0,start=0;stage.innerHTML='<div class="game-view"><h2 class="game-title">⚡ Speed Tap</h2><p class="muted">Tap the target 20 times as fast as possible.</p><button class="btn btn-primary game-btn" id="speedTap">START</button><div id="speedMsg" class="big-number">0 / 20</div></div>';const b=$('#speedTap');b.onclick=()=>{if(!start){start=Date.now();n=0;b.textContent='TAP!'}n++;$('#speedMsg').textContent=n+' / 20';if(n>=20){const ms=Date.now()-start;toast('Speed Tap: '+ms+' ms');saveScore('reaction2',Math.max(1,Math.floor(20000/ms*100)));start=0;b.textContent='TRY AGAIN'}}}
function arcade(mode){
 const titles={quickdraw:['🔫 Quick Draw','Tap only when GO appears.'],maze:['🧩 Maze Escape','Use the arrows to reach the exit.'],typing:['⌨️ Typing Rush','Type the word before time runs out.'],dice:['🎲 Dice Duel','Roll against the computer.'],oddone:['🔎 Odd One Out','Tap the tile with the different color.'],colormemory:['🧠 Color Memory','Remember the highlighted tile.'],safegrid:['🛡️ Safe Grid','Reach the bottom without stepping on a trap.']};
 if(mode==='jmbdash'){jmbDash();return}
 const t=titles[mode];stage.innerHTML='<div class="game-view"><h2 class="game-title">'+t[0]+'</h2><p class="muted">'+t[1]+'</p><div id="arcadeArea" class="target-stage"></div><div class="actions" style="justify-content:center"><button class="btn btn-primary" id="arcadeStart">START</button></div><div id="arcadeMsg" class="score-readout">Ready</div></div>';
 const a=$('#arcadeArea'),m=$('#arcadeMsg'),start=$('#arcadeStart');
 if(mode==='quickdraw'){start.onclick=()=>{start.disabled=true;a.textContent='WAIT…';const t0=Date.now();setTimeout(()=>{a.textContent='GO!';a.style.background='rgba(53,230,162,.25)';const go=Date.now();a.onclick=()=>{const ms=Date.now()-go;m.textContent=ms+' ms';saveScore('quickdraw',Math.max(1,2000-ms));start.disabled=false;start.textContent='TRY AGAIN';a.onclick=null}},1000+Math.random()*2500)}}
 if(mode==='maze'){let x=1,y=1,ex=8,ey=8;const walls=new Set(['2,1','2,2','2,3','4,3','5,3','6,3','6,4','6,5','3,6','4,6','5,6','7,7']);const draw=()=>{a.innerHTML='';a.style.display='grid';a.style.gridTemplateColumns='repeat(9,1fr)';for(let yy=0;yy<9;yy++)for(let xx=0;xx<9;xx++){const b=document.createElement('button');b.textContent=xx===x&&yy===y?'●':xx===ex&&yy===ey?'🏁':walls.has(xx+','+yy)?'':'·';b.style.cssText='border:1px solid rgba(255,255,255,.05);background:'+(walls.has(xx+','+yy)?'#22283b':'#0c1220')+';color:#fff';a.append(b)}};const move=(dx,dy)=>{const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>8||ny>8||walls.has(nx+','+ny))return;x=nx;y=ny;draw();if(x===ex&&y===ey){m.textContent='Escaped!';saveScore('maze',100)}};start.onclick=()=>{x=1;y=1;draw()};window.addEventListener('keydown',e=>{if(current!=='maze')return;const d={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];if(d)move(...d)});draw()}
 if(mode==='typing'){const words=['portal','minecraft','jmbhub','rocket','diamond','pixel','community'];let word='';start.onclick=()=>{word=words[Math.floor(Math.random()*words.length)];a.innerHTML='<input id="typeIn" class="tool-input" placeholder="'+word+'"><div class="big-number">'+word+'</div>';const inp=$('#typeIn');inp.focus();let end=Date.now()+8000;const iv=setInterval(()=>{if(Date.now()>end){clearInterval(iv);m.textContent='Time up';return}if(inp.value.toLowerCase()===word){clearInterval(iv);m.textContent='Correct!';saveScore('typing',Math.max(1,Math.floor((end-Date.now())/10)));start.textContent='NEXT'}} ,80)}}
 if(mode==='dice'){start.onclick=()=>{const me=1+Math.floor(Math.random()*6),ai=1+Math.floor(Math.random()*6);m.textContent='You '+me+' • Computer '+ai+' • '+(me>ai?'You win!':me<ai?'Computer wins':'Draw');if(me>ai)saveScore('dice',20)}}
 if(mode==='oddone'){start.onclick=()=>{const odd=Math.floor(Math.random()*25),base=Math.floor(Math.random()*360),items=Array.from({length:25},(_,i)=>'<button data-i="'+i+'" style="height:52px;border:0;border-radius:10px;background:hsl('+base+(i===odd?'+ 18':'')+',70%,55%);color:transparent">.</button>').join('');a.style.display='grid';a.style.gridTemplateColumns='repeat(5,1fr)';a.innerHTML=items;a.onclick=e=>{const i=Number(e.target.dataset.i);if(i===odd){m.textContent='Correct!';saveScore('oddone',50)}else m.textContent='Try again'}}}
 if(mode==='colormemory'){let target=0;start.onclick=()=>{target=Math.floor(Math.random()*16);a.style.display='grid';a.style.gridTemplateColumns='repeat(4,1fr)';a.innerHTML=Array.from({length:16},(_,i)=>'<button data-i="'+i+'" style="height:60px;border:1px solid var(--line);background:'+(i===target?'#7c5cff':'#10162a')+'"></button>').join('');setTimeout(()=>a.querySelectorAll('button').forEach(b=>b.style.background='#10162a'),900);a.onclick=e=>{if(Number(e.target.dataset.i)===target){m.textContent='Perfect memory!';saveScore('colormemory',60)}else m.textContent='Missed — try again'}}}
 if(mode==='safegrid'){let pos=0,traps=[];start.onclick=()=>{pos=0;traps=Array.from({length:7},()=>Math.floor(Math.random()*20)+5);a.style.display='grid';a.style.gridTemplateColumns='repeat(5,1fr)';a.innerHTML=Array.from({length:25},(_,i)=>'<button data-i="'+i+'" style="height:55px;border:1px solid var(--line);background:#10162a">'+(i===0?'▶':'')+'</button>').join('');a.onclick=e=>{const i=Number(e.target.dataset.i);if(i!==pos)return;if(traps.includes(i)){m.textContent='Trap!';start.disabled=false;return}pos++;if(pos===24){m.textContent='Safe!';saveScore('safegrid',100)}else m.textContent='Step '+pos+'/24'}}}
}
function jmbDash(){
 stage.innerHTML='<div class="game-view"><h2 class="game-title">🟪 JMB Dash</h2><p class="muted">An original rhythm-runner game. Tap JUMP to clear obstacles.</p><canvas id="dashCanvas" width="760" height="300" style="width:min(760px,100%);height:auto;border:1px solid var(--line);border-radius:18px;background:linear-gradient(#11152a,#080b15);touch-action:none"></canvas><div class="actions" style="justify-content:center"><button class="btn btn-primary game-btn" id="dashJump">JUMP</button><button class="btn btn-ghost" id="dashStart">START</button></div><div id="dashScore" class="score-readout">Distance: 0</div></div>';
 const c=$('#dashCanvas'),ctx=c.getContext('2d'),jump=$('#dashJump'),start=$('#dashStart'),scoreEl=$('#dashScore');let x=90,y=220,vy=0,obs=[],run=false,score=0,raf;
 function reset(){x=90;y=220;vy=0;obs=[];score=0;for(let i=0;i<7;i++)obs.push({x:520+i*170,h:25+Math.random()*45})}
 function doJump(){if(run&&y>=220){vy=-11}}
 function frame(){ctx.clearRect(0,0,760,300);ctx.fillStyle='#10172b';ctx.fillRect(0,0,760,300);ctx.fillStyle='#7c5cff';ctx.fillRect(x,y,28,28);ctx.fillStyle='#00d4ff';ctx.fillRect(0,248,760,4);ctx.fillStyle='#ff5578';for(const o of obs){o.x-=5;ctx.fillRect(o.x,248-o.h,30,o.h);if(o.x<118&&o.x+30>90&&y+28>248-o.h){run=false;cancelAnimationFrame(raf);toast('JMB Dash — '+score);saveScore('jmbdash',score);start.textContent='RESTART'}}if(obs[0]?.x<-40){obs.shift();obs.push({x:obs[obs.length-1].x+170,h:25+Math.random()*55});score++;scoreEl.textContent='Distance: '+score}vy+=.55;y+=vy;if(y>220){y=220;vy=0}if(run)raf=requestAnimationFrame(frame)}
 jump.onpointerdown=e=>{e.preventDefault();doJump()};c.onpointerdown=e=>{e.preventDefault();doJump()};window.addEventListener('keydown',e=>{if(current==='jmbdash'&&(e.code==='Space'||e.code==='ArrowUp'))doJump()});start.onclick=()=>{cancelAnimationFrame(raf);reset();run=true;start.textContent='RUNNING';frame()}
 reset();
}
function guesscolor(){const target={r:Math.floor(Math.random()*256),g:Math.floor(Math.random()*256),b:Math.floor(Math.random()*256)};stage.innerHTML='<div class="game-view"><h2 class="game-title">🌈 Color Guess</h2><div id="guessColorBox" class="result-box" style="height:180px"></div><p class="muted">Enter RGB values.</p><div class="form-grid"><input id="gr" class="tool-input" type="number" min="0" max="255" placeholder="R"><input id="gg" class="tool-input" type="number" min="0" max="255" placeholder="G"><input id="gb" class="tool-input" type="number" min="0" max="255" placeholder="B"></div><button class="btn btn-primary" id="colorGuessBtn">Guess</button><p id="colorGuessMsg"></p></div>';$('#guessColorBox').style.background='rgb('+target.r+','+target.g+','+target.b+')';$('#colorGuessBtn').onclick=()=>{const d=Math.abs(Number($('#gr').value)-target.r)+Math.abs(Number($('#gg').value)-target.g)+Math.abs(Number($('#gb').value)-target.b);const score=Math.max(1,100-Math.floor(d/8));$('#colorGuessMsg').textContent='Score: '+score+'/100';saveScore('guesscolor',score)}}
const render={snake,click:clickRush,reaction,target,dodge,tap,number,math,color,whack,memory,tic,stack,coin,flappy,'2048':mini2048,rps,coinflip,higher,word,aim,simon,pong,lights,connect,reaction2,guesscolor,jmbdash:()=>arcade('jmbdash'),quickdraw:()=>arcade('quickdraw'),maze:()=>arcade('maze'),typing:()=>arcade('typing'),dice:()=>arcade('dice'),oddone:()=>arcade('oddone'),colormemory:()=>arcade('colormemory'),safegrid:()=>arcade('safegrid')};
function switchGame(name){current=name;const info=games.find(x=>x[0]===name)||games[0];setHeader(name);loadBoard(name);stage.innerHTML='';render[name]();openWorkspace(stage,{title:info[2],description:info[3]})}
(async()=>{user=await guard();renderLibrary();})();